spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 6
      minimum-idle: 2
      idle-timeout: 60000
      max-lifetime: 600000
      connection-timeout: 10000
      leak-detection-threshold: 30000
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
feign:
  plans-service:
    url: ${FEIGN_PLANS_SERVICE_URL}
  academic-service:
    url: ${FEIGN_ACADEMIC_SERVICE_URL}
  finance-service:
    url: ${FEIGN_FINANCE_SERVICE_URL}

uebi:
  jwt:
    secret: ${JWT_SECRET}
logging:
  level:
    root: WARN
    br.com.uebiescola: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
